### PR TITLE
added hero image placeholder to text pages

### PR DESCRIPTION
**Pull request by valieff**

### CODE REVIEW

**Comment by sorokinvj** [comment]
@valieff Vova, looks great! Don't you think though its better to position content of the text page in the center? right now the empty space on the right side feels a bit off, just a suggestion though, feel free to use it or loose it

**Review by sorokinvj — APPROVED** [review]

**Review by sorokinvj — CHANGES_REQUESTED** [review]
I am afraid 'cover' is not working, take a look at how a new picture fits the parent,  I uploaded it just now

Screenshot 2022-09-16 at 15 51 54

**Comment by valieff** [comment]
Tweaked layout so that it looks better on desktop. Also fixed image width.

**Review by sorokinvj — APPROVED** [review]
it looks so cool now, thanks!

**Pull request merged**
